### ISSUE TITLE
New lua bug since bcc

### ISSUE THREAD

**Issue by Paroyer** [exochron/MouseoverPortrai#2]
During pre-patch everything was working fine, but since the dark portal opened I got this lua error trigering pretty often:

MouseoverPortrai\MouseoverPortrai-2.2.lua:67: attempt to compare nil with number
[string "@MouseoverPortrai\MouseoverPortrai-2.2.lua"]:67: in function <MouseoverPortrai\MouseoverPortrai.lua:59>
[string "@MouseoverPortrai\MouseoverPortrai-2.2.lua"]:139: in function <MouseoverPortrai\MouseoverPortrai.lua:123>
[string "=[C]"]: ?

Locals:
currentCast = <table> {
}
currentChannel = <table> {
1 = "Using Steam Tonk Controller"
2 = "Using Steam Tonk Controller"
3 = 133015
4 = 3461645
5 = 3761645
6 = false
7 = 45257
}
(*temporary) = 3761645
(*temporary) = nil
(*temporary) = 5
(*temporary) = 3461645
(*temporary) = 3761645
(*temporary) = false
(*temporary) = "attempt to compare nil with number"
indexCastID = 7
lastCast = <table> {
}
indexEndTimeMS = 5
indexChannelSpellId = 8
lastChannel = <table> {
}
indexCastingSpellId = 9
indexCastingNotInterruptible = 8
indexChannelNotInterruptible = 7

**Comment by exochron** [comment]
Thanks again for reporting this.
As mentioned [on curseforge](https://www.curseforge.com/wow/addons/mouseover-portrai/issues/4). It should be fixed with version 2.3
